### ISSUE TITLE
Mikrotik and Ubiquiti responded already

### ISSUE THREAD

**Issue by CodeBrauer** [kristate/krackinfo#1]
* [Mikrotik](https://forum.mikrotik.com/viewtopic.php?f=21&t=126695)
* [Ubiquiti](https://community.ubnt.com/t5/UniFi-Beta-Blog/FIRMWARE-3-9-3-7537-for-UAP-USW-has-been-released/ba-p/2098382)

**Comment by kristate** [comment]
Thanks -- Will add to report
