### ISSUE TITLE
Redhat update

### ISSUE THREAD

**Issue by dgcurtis** [kristate/krackinfo#139]
Redhat updated wpa_supplicant for RHEL7 on 10/17 and RHEL6 on 10/18

https://access.redhat.com/errata/RHSA-2017:2907
https://access.redhat.com/errata/RHSA-2017:2911

**Comment by kristate** [comment]
Were these merged?

**Comment by 4ndrej** [comment]
Well, I detected this and sent pull request #140 for that data. It seems it's already merged.

**Comment by kristate** [comment]
Thanks @4ndrej ! Closing
