### ISSUE TITLE
Zoom Telephonics is not listed

### ISSUE THREAD

**Issue by subscriptionblocker** [kristate/krackinfo#167]
Believe their products used Ralink Chips

**Comment by zeadope-zz** [comment]
Modems / routers are not affected (unless they have a mode to act as a client (-bridge). Fixes have to be made a the client side.

**Comment by subscriptionblocker** [comment]
These pocket routers do function as clients. The way we use them.

**Comment by eaglerainbow** [comment]
@subscriptionblocker Please review #228 and object, if this does not look suitable for you.
