### ISSUE TITLE
BearExtender is not listed

### ISSUE THREAD

**Issue by subscriptionblocker** [kristate/krackinfo#170]
https://www.amazon.com/gp/product/B00VW4M0WO/ref=oh_aui_detailpage_o06_s00?ie=UTF8&psc=1

Believe it is Ralink based.

**Comment by zeadope-zz** [comment]
Can you do a pull request? Company changed it’s name to [Bearify](https://www.bearifi.com/blogs/news/bearifi-the-new-name-of-bearextender).

**Comment by subscriptionblocker** [comment]
https://www.bearifi.com
