### ISSUE TITLE
D-Link Response

### ISSUE THREAD

**Issue by subscriptionblocker** [kristate/krackinfo#173]
Thank you for contacting D-Link Email Support. 

 

As what I have read on your e-mail, you're looking for a WPA2 patch in response to KRACK.

 

D-Link has immediately taken actions to investigate this matter. This security concern appears to be an industry-wide issue that will require firmware patches to be provided from the relevant semiconductor chipset manufacturers.

 

D-Link has requested assistance from the chipset manufacturers. As soon as the firmware patches are received from the chipset manufacturers, we will post them on our websites immediately. Please take the following important actions to help protect your privacy:

 

1.  Iis highly recommended to use encrypted communications protocols such as VPN or HTTPS, especially when delivering confidential information.

2. Check our website regularly for the newest firmware updates.

Thank you for networking with D-Link .

**Comment by zeadope-zz** [comment]
Thanks. I see you have opened a few issues. Can you do a pull request for these? And preferably include a link to an official response. Or else add a comment, you can also link a screenshot a communication with support. (See entry iRobot). 

Dlink is listed as entry D-Link.

**Comment by eaglerainbow** [comment]
Same information is also available at http://supportannouncement.us.dlink.com/announcement/publication.aspx?name=SAP10075, resp. on http://www.dlink.com/uk/en/support/support-news/2017/october/18/response-to-krack-wpa2-key-reinstallation-attack-security-vulnerability
