### ISSUE TITLE
To what is "Last Updated" referring?

### ISSUE THREAD

**Issue by eaglerainbow** [kristate/krackinfo#191]
It's unclear to me to what the date in column "Last Updated" in table "Vendor Response (complete)" is referring. Does it mean
* when the line was last updated (thus, virtually duplicating the git history information)?
* when the response by the vendor was last updated?

**Comment by zeadope-zz** [comment]
I’ do the first bullet. Not everyone knows how github works that visits this page.

**Comment by eaglerainbow** [comment]
Fine with me; we just have to make sure that we all apply the same approach 😁 

@kristate If that also fits to your expectation, then it's ok with me and thus we can close the issue here.

**Comment by kristate** [comment]
@eaglerainbow thanks, @zeadope is correct: when our directory was last updated. Closing.
