### ISSUE TITLE
Add NVIDIA (SHIELD TV update available)

### ISSUE THREAD

**Issue by edjm** [kristate/krackinfo#211]
NVIDIA is providing a fix for their SHIELD TV (Android TV) with firmware version 6.1.

https://shield.nvidia.com/support/nvidia-android-tv/release-notes/1

> The latest monthly Android security updates including fixes for WPA2 protocol (KRACK)

**Comment by NuclearPhoenixx** [comment]
That's good news. Unfortunately, no patches for the Shield tablets yet...
