### ISSUE TITLE
OnePlus patched

### ISSUE THREAD

**Issue by maxcodes** [kristate/krackinfo#212]
I have a OnePlus 2 and received an OTA update that explicitly stated KRACK was patched (OxygenOS).
Took a screenshot, will add as soon as I get my hands on my phone.

**Comment by maxcodes** [comment]
![screenshot_20171031-114424](https://user-images.githubusercontent.com/6092334/32380876-e2a01006-c076-11e7-9407-ff8694164909.png)

**Comment by CodeBrauer** [comment]
Also OnePlus 5 got fixed:
- https://forums.oneplus.net/threads/oxygenos-4-5-14-ota-for-the-oneplus-5.671640/
- https://www.xda-developers.com/oneplus-5-oxygenos-patch-krack-bugs/

Status for OnePlus 3 unknown

**Comment by eaglerainbow** [comment]
@CodeBrauer and @maxcodes Could you please review PR #225 (see also https://github.com/eaglerainbow/krackinfo/tree/oneplus ) to verify if everything's correct for OnePlus? To be honest, my experience is close to zero on these devices and I had the impression that I only understood half of what I was doing there 😀 
Thanks!

**Comment by CodeBrauer** [comment]
~~As I see -OnePlus2 and OnePlus5 got fixed - OnePlus 3 and 3T still no info its patched or even affected~~
Seems to be updated
https://www.androidsage.com/2017/11/08/oneplus-3t-update-wifi-krack-wpa2-blueborne-patch/

**Comment by kristate** [comment]
#225 was merged -- should we close this?

**Comment by eaglerainbow** [comment]
>  should we close this?

From my point of view: +1

**Comment by CodeBrauer** [comment]
I'm an owner of the OnePlus 3. I never got OxygenOS 4.5.2 - I just got Oxygen OS 5.0.0 a week ago. But the android security patch level is still Sep 2017 - so is it fixed or not?
- www.androidsage.com is mentioning only HydrogenOS **not** OxygenOS -> Hydrogen is China only
- It's not mentioned in the changelog: https://forums.oneplus.net/threads/oxygenos-5-0-android-o-ota-for-the-oneplus-3-and-3t.684228/
- Question related, currently unanswered: https://forums.oneplus.net/threads/does-oos-5-0-comes-with-krack-fix.691577/

The changelog of OnePlus 5 mentioned "Fixed Wi-Fi WPA2 security issue" - Which is missing for OnePlus 3(T).

**Comment by eaglerainbow** [comment]
Given that https://forums.oneplus.net/threads/oxygenos-5-0-android-o-ota-for-the-oneplus-3-and-3t.684228/ states that OxygenOS 5.0.0 is based on Android 8.0, and Android 8.0 still may be vulnerable to KRACK (as it was released *before* the CVE's got made public), and your Android Security Patch Level is before 2017-11-06 (which is the "magical date" for Android -- at least what we know from the rest of the Android ecosystem), I currently would **expect** that your phone still is vulnerable (which is anyhow also the safe assumption).  
However, as long as there is no official statement by the manufacturer, you may never know it for sure...

**Comment by CodeBrauer** [comment]
Today OP3 got the update to Android Security Patch Level Dezember 

> " - Updated Android security patch to December"

From: https://forums.oneplus.net/threads/oxygenos-5-0-1-ota-update-for-oneplus-3-and-3t.733145/
