### ISSUE TITLE
Android Security Bulletin—November 2017 has KRACK patch

### ISSUE THREAD

**Issue by rocketwidget** [kristate/krackinfo#214]
https://source.android.com/security/bulletin/2017-11-01

**Comment by Gunni** [comment]
I already opened https://github.com/kristate/krackinfo/pull/216 it has not been merged yet

**Comment by eaglerainbow** [comment]
see also PR #220

**Comment by eaglerainbow** [comment]
@rocketwidget and @Gunni : Please feel encouraged to review #220

**Comment by kristate** [comment]
Sorry for the tardiness! I commented over at #220
