### ISSUE TITLE
Entries should be separated into two tables: Client OS and AP Vendor

### ISSUE THREAD

**Issue by joshuarli** [kristate/krackinfo#27]
KRACK is mostly client based, which is why I think the entries should be separated into two tables: Client OS and AP vendor. Not going to submit a PR for this since it would merge conflict with all the current PRs, just a suggestion.

**Comment by kristate** [comment]
Yes, perhaps -- but at the moment it's easier to just search for a vendor -- also many lists do not take this into account. It is a logical suggestion, though!

**Comment by joshuarli** [comment]
Fair point. If the list gets obnoxiously large, I would consider this change.
