### ISSUE TITLE
Unsubstantiated Information

### ISSUE THREAD

**Issue by joshuarli** [kristate/krackinfo#42]
The information added in commit 4bfa25b5e2512ec15ee8c09f4ce29331a4cb55d8 seems unsubstantiated and out-of-place to me.

I personally think it would be best to keep it simple - let other websites and resources explain the implications, or the information could be merged into sections "Attacks that ...".

**Comment by kristate** [comment]
Thanks for your opinion! Pull requests are welcome to add more information.
