### ISSUE TITLE
AVR vendors

### ISSUE THREAD

**Issue by stintel** [kristate/krackinfo#43]
Please add vendors of AVR equipment (Denon/Marantz, Onkyo, Pioneer, ...)
As I own a Marantz receiver with WiFi, I [Tweeted @MarantzEurope](https://twitter.com/stintel/status/920032037297410049)

**Comment by kristate** [comment]
Good idea! Let me get on it.

**Comment by stintel** [comment]
Thanks!

**Comment by kristate** [comment]
Certainly! Thanks
