### ISSUE TITLE
IoT Vendors

### ISSUE THREAD

**Issue by cladmonitor** [kristate/krackinfo#45]
Probably should add:
Nest Labs - Doesn't seem to be taking things seriously "No known attacks can be carried out against our hardware"  was the reply I was told vai support. 
Ring - Per support "They promise to update public shortly, actively working with developers."
Yi (Xiaoyi) -  Waiting on a reply.

**Comment by kristate** [comment]
Good idea, let me add them

**Comment by kristate** [comment]
Added -- thanks!
