### ISSUE TITLE
Raspbian (Raspberry Pi)

### ISSUE THREAD

**Issue by zeadope-zz** [kristate/krackinfo#52]
Fixed in Debian but not yet included in Raspbian repository.

**Comment by ctoor** [comment]
Got an update “wpa...“ five minutes ago on my PI3.
Don't know: it is the security solution?!

**Comment by Spydar007** [comment]
Yes, wpasupplicant has now been patched in Raspbian.

**Comment by kristate** [comment]
Can we get a link to an official statement?

**Comment by kristate** [comment]
I added some info for Raspbian, but I need that official statement URL

**Comment by zeadope-zz** [comment]
I got my info from https://raspberrypi.stackexchange.com/questions/73879/rpi-vulnerable-for-wi-fi-wpa2-krack-attack
Basically Raspbian is Debian but different architecture.

**Comment by skatsikeas** [comment]
I have found this earlier:
https://www.debian.org/security/2017/dsa-3999
On the bottom it specifically says for Debian jessie and Debian stretch

**Comment by zeadope-zz** [comment]
@sotos183 problem is that Rapsbian doesn’t use the same repo: https://www.raspbian.org/RaspbianRepository

**Comment by Spydar007** [comment]
A simple `apt-cache show wpasupplicant` shows that Raspbian now has version `2:2.4-1+deb9u1`, which is the Debian version that patches it.

**Comment by zeadope-zz** [comment]
We’re not fully there yet:
> Update (20171002 01:38):
> The fixes for raspbian Jessie and Stretch should now be in the public raspbian repo.
> The fix for raspbian buster should follow in a few hours.
> I do not know if/when there will be a fix for wheezy.
[source](https://raspberrypi.stackexchange.com/a/73908)

**Comment by kristate** [comment]
Okay -- I will update the comments area

**Comment by kristate** [comment]
Any updates?

**Comment by zeadope-zz** [comment]
Nothing official yet.

But looking at the Debian source all flavors, (except for the older wheezy), should be patched by now.

**Comment by kristate** [comment]
Maybe someone should push them for an official update, blog or otherwise.

**Comment by kristate** [comment]
@raspberrypi

**Comment by kristate** [comment]
What is the current status for RPi? No blog posts??

**Comment by 4ndrej** [comment]
I think that you can assume that releasing the patched wpa_supplicant IS the official response.

**Comment by Spydar007** [comment]
There has been no official response. Raspbian have silently released the patched wpa_supplicant into stable.

**Comment by zeadope-zz** [comment]
@kristate @4ndrej @Spydar007 Fix has been released already. See Repo [LINK](http://archive.raspbian.org/raspbian/pool/main/w/wpa/).
I don't expect an official statement since they rely Debian. Closing issue for now.
