### ISSUE TITLE
Why is there some Japanese text?

### ISSUE THREAD

**Issue by deoxxa** [kristate/krackinfo#56]
Not an issue, just a curiosity. Why are two of the headings paraphrased in Japanese? A friend and I couldn't figure out the motivation but we're darned curious.

**Comment by asgs** [comment]
in case you didn't notice, the author's profile shows his location as Japan

**Comment by kristate** [comment]
Hi, this started as a page for Japanese people, but english is best in these situations -- expect removal when I get the JP page up.

Thanks!
