### ISSUE TITLE
OnePlus

### ISSUE THREAD

**Issue by SeanFeldman** [kristate/krackinfo#57]
[OnePlus](https://oneplus.net/) is not on the list

**Comment by asgs** [comment]
LineageOS has made [their commits](https://github.com/LineageOS/android_external_wpa_supplicant_8). OxygenOS [doesn't seem](https://github.com/OnePlusOSS/android_external_wpa_supplicant_8) to have done theirs

Users like me who are stuck on the now-discontinued CyanogenOS should make their move to one of the above ROMs (preferably LineageOS)

**Comment by kristate** [comment]
Can we get a pull request for this?

**Comment by SeanFeldman** [comment]
@kristate PR raised.
