### ISSUE TITLE
TP-Link official statement

### ISSUE THREAD

**Issue by Spydar007** [kristate/krackinfo#68]
TP-Link have stated they will be updating [this page](http://forum.tp-link.com/showthread.php?101094-Security-Flaws-Severe-flaws-called-quot-KRACK-quot-are-discovered-in-the-WPA2-protocol) with details when they have verified specific products as vulnerable.

**Comment by kristate** [comment]
Updated -- thanks!

**Comment by Spydar007** [comment]
TP-Link have now issued [this](http://www.tp-link.com/us/faq-1970.html).
