### ISSUE TITLE
Mojo Networks missing from Krack page

### ISSUE THREAD

**Issue by cheriemartin** [kristate/krackinfo#77]
Hi Kris,

Mojo Networks would like to be included on your Vendor Patch Matrix for the WPA2. Not only have we already upgraded our cloud server with the fix, we have an upgrade available for all Mojo APs. Further, Mojo is the only vendor with built-in MAC spoofing and Man-in-the-Middle protection that helps users mitigate the majority of the client side vulnerabilities until software updates are available for those clients. (other vendors may cover those features, but only to customers who purchase an extra license/product add on).

You can find info at the following URLs. If you have any questions, please feel free to contact me directly at cherie.martin@mojonetworks.com

WPA Vulnerability Announcement (https://www.mojonetworks.com/wpa2-vulnerability)

Blog: WPA2 Key Reinstallation Vulnerabilities (KRACK) Explained (http://blog.mojonetworks.com/wpa2-vulnerability)

Mitigation Plan on Mojo Support Portal
https://support.mojonetworks.com/support/solutions/articles/9000134420-wpa2-wpa-key-reinstall-vulnerabilities

Thanks!
Cherie

**Comment by kristate** [comment]
Certainly, thanks for the heads up -- if you would kindly issue a pull request, I can merge it with the current vendor matrix.

**Comment by cheriemartin** [comment]
sadly, not sure I understand what you need. I see the pull request page.  However, this is my very first time on github, and not sure what you are looking for. Do you need the info for mojo that matches the columns in your matrix?  what format?

Please advise.

Cher

**Comment by cheriemartin** [comment]
I have spent the last couple hours going through the tutorials on how to clone and modify a GIT file so that I can add a pull request, to no avail. I know the changes that need to be made, just can't seem to figure out how to stage them for you. I am not a dev expert, rather a marketing person with just enough technical prowess to get myself in trouble.

Any guidance you can give would be helpful.

Cher

**Comment by cheriemartin** [comment]
in Patch matrix:
Mojo Networks - software update available

in vendor response matrix
Mojo Networks | https://www.mojonetworks.com/wpa2-vulnerability | Update to cloud management platform completed. In order to mitigate client-side vulnerabilities, Mojo recommends upgrading AP software to version 8.5, and enabling MAC Spoofing and Man-in-the-middle attack prevention with built-in WIPs. | 2017-10-17 | 2017-10-17

**Comment by dualbus** [comment]
Hey, for this change, I've created the following pull request: https://github.com/kristate/krackinfo/pull/86

**Comment by kristate** [comment]
Thanks! closing

**Comment by cheriemartin** [comment]
thank you!  I really tried to figure it out before just including the info
for you.



Check out Mojo's latest blog!
Fanning the Flames of Rebellion with Honor <http://blog.mojonetworks.com/>

Cherie Martin
Senior Manager, Sales Enablement
Mojo Networks
408-799-4097

At Mojo Networks, we are revolutionizing WiFi through the power of the
cloud and open standards. We liberate networks from proprietary hardware
and utilize the full power of the cloud to deliver cognitive WiFi: a
self-driving network that makes things remarkably simple and reliable at
massive scale. Mojo Networks' innovations empower IT with better user
experiences, more options, and more velocity, all at much lower costs.
Request a free demo of Mojo Cloud managed Wifi at www.mojonetworks.com.

Follow us on Twitter!  @mojonetworks_
