### ISSUE TITLE
CZ.NIC Turris OS (OpenWrt-based)

### ISSUE THREAD

**Issue by spike411** [kristate/krackinfo#8]
CZ.NIC Turris team is testing a fix (backported from hostapd upstream):
https://gitlab.labs.nic.cz/turris/openwrt/commit/a60970f33f65bfb1d531ce822bfd28ee049a702f
via
https://forum.turris.cz/t/major-wpa2-vulnerability-to-be-disclosed/5363/8

Homepage: https://www.turris.cz/en/

**Comment by kristate** [comment]
Thanks again!
