### ISSUE TITLE
Sonos response - aware and looking into

### ISSUE THREAD

**Issue by abulgatz** [kristate/krackinfo#90]
Sonos has stated here: https://en.community.sonos.com/ask-a-question-228987/is-sonos-vulnerable-to-the-krack-attack-6792188

> Ryan S, Community Manage said:
>
> Hi everyone,
> 
> We're aware of the issues with WPA2 and our team is working to determine any ramifications this may have for Sonos players.
> 
> We appreciate your concern and thanks for reaching out.

**Comment by kristate** [comment]
Merged? Closing.
