### ISSUE TITLE
ecobee reponse - claims not vulnerable

### ISSUE THREAD

**Issue by abulgatz** [kristate/krackinfo#91]
Not sure I believe them, but I have contacted ecobee support and they claim that ecobees are not vulnerable

Their full response as of 10:21am on 10-17:

> Hello,
> 
> Thank you for contacting ecobee technical support today.
> 
> ecobee is aware of the industry-wide vulnerability in WPA2 referred to as KRACK. The security of our customers is very important to us, and we have confirmed that ecobee device security is not impacted by this issue.
> 
> Regards

**Comment by zeadope-zz** [comment]
Can you get Ecobee to make an official statement? Maybe from twitter so that a link can be added to the list.

**Comment by abulgatz** [comment]
I can't *make* ecobee do anything, but I'll certainly ask.

**Comment by zeadope-zz** [comment]
@abulgatz Sorry for my poor choice of words. Thanks!

**Comment by abulgatz** [comment]
No problem, I was joking anyway. I wish I could make ecobee do a number of things, like support longer range for their remote sensors or implement a local web interface.

Anyway, I have replied to my support ticket asking for an official response. I'll update if anything comes of it.

**Comment by kristate** [comment]
Merged info on Ecobee -- closing;
